name: test262

on:
  push: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test262:
    name: Run test262 tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js latest
        uses: actions/setup-node@v3
        with:
          node-version: "*"
          cache: "yarn"
      - name: Build
        run: make bootstrap
        env:
          BABEL_ENV: test
      - name: Setup test runner
        run: |
          git clone --depth=1 --recurse-submodules https://github.com/babel/babel-test262-runner
          cd babel-test262-runner
          npm ci
          npm i tap-mocha-reporter --save-dev
          node lib/download-node
      - name: Run test262
        run: |
          cd babel-test262-runner
          node lib/run-tests arrow | tee ~/test262.tap
        env:
          BABEL_PATH: ".."
      - name: Output Test262 results
        run: |
          cd babel-test262-runner
          cat ~/test262.tap | $(npm bin)/tap-mocha-reporter spec || true
      - name: Create artifact with report results
        uses: actions/upload-artifact@v3
        with:
          name: test262-result
          path: ~/test262.tap
